CREATE TABLE ANIMAL (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DISCOVER_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    DISCOVER_TIME TIME NOT NULL DEFAULT CURRENT_TIME,
    SPECIES VARCHAR(50),
    KIND VARCHAR(50),
    AVG_WEIGHT NUMERIC(7,1),
    AVG_SIZE NUMERIC(3,1),
    CUTENESS INTEGER CHECK (CUTENESS>=0 AND CUTENESS<=10),
    PRIMARY KEY (ID)
);

CREATE TABLE SPECIES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    DISCOVER_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    DISCOVER_TIME TIME NOT NULL DEFAULT CURRENT_TIME,
    SPECIES VARCHAR(50),
    PRIMARY KEY (ID)
);
